import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center p-4">
        <div className="relative w-max overflow-hidden">
          <div className="absolute inset-0 -z-10 bg-[#fd5530] mix-blend-screen" />
          <Image
            src={
              "https://uploads-ssl.webflow.com/640eeddd1d1ef84438c097d7/640f394d495e6943529531e0_zso-model_walking-p-800.jpg"
            }
            alt={"Image"}
            width={800}
            height={824}
            className="absolute bottom-1/2 right-1/2 -z-20 h-[100.5%] translate-x-1/2 translate-y-1/2 object-cover"
          ></Image>
        </div>
      </main>
    </>
  );
}
